IllinoisSemCorrelations
=================================================
This report takes an SEM approach to fitting the Illinois Basin replicates

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of two directories.-->
```{r, echo=F, message=F} 
# cat("Working directory: ", getwd())

  opts_knit$set(root.dir='../../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# cat("Working directory: ", getwd())
require(knitr)
opts_chunk$set(
  results='show', 
  comment = NA, 
  tidy = FALSE,
  fig.width = 6.5, 
  fig.height = 4, 
  fig.path = 'Figures/'
)
# dpi = 400,
# out.width = "650px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.

echoChunks <- TRUE
options(width=120) #So the output is 50% wider than the default.
read_chunk("./Analysis/IllinoisSemCorrelations/IllinoisSemCorrelations.R") #This allows knitr to call chunks tagged in the underlying *.R file.
```
<!-- Load the packages.  Suppress the output when loading packages. --> 
```{r LoadPackages, echo=echoChunks, message=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r DeclareGlobals, echo=echoChunks, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=echoChunks, message=FALSE}
```

<!-- Load the datasets.   -->
```{r LoadData, echo=echoChunks, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r TweakData, echo=echoChunks, results='show', message=FALSE}
```

## Notes


# Marginals
```{r Marginals, echo=echoChunks, message=TRUE}
```

# Models
```{r Models, echo=echoChunks, message=TRUE}
```

# Questions
## Unanswered Questions
 1. - - - 
 
## Answered Questions
 1. - - - 
 
# Session Information
For the sake of documentation and reproducibility, the current report was build on a system using the following software.

```{r session_info, echo=FALSE}
cat("Report created by", Sys.info()["user"], "at", strftime(Sys.time(), "%Y-%m-%d, %H:%M %z"))
sessionInfo()
```
